Lidar page adjust, SM numbers fix
TNRIS/tnris.org pull request #119
Opened 2019-11-22 23:11 UTC by christoball

closes #114, closes #4

2019-11-22 23:13 UTC, christoball commented
also closes #113

2019-11-25 19:53 UTC, adambreznicky requested changes
![Selection_016](https://user-images.githubusercontent.com/5650145/69572971-ce580580-0f8a-11ea-87a7-8044dadc8b80.png)

sass changes have effected the main /stratmap by the numbers section so the text is not legible

2019-11-25 20:02 UTC, adambreznicky commented
i'm not sure how the changes close #4 ? there is no new lidar status map thumbnail link on the stratmap landing page...
i see changes to the organization of the lidar page, but the content is the same with only an exception of an anchor text link to stratmap contracts.

2019-11-25 20:03 UTC, adambreznicky requested changes
i'm not sure how the changes close #4 ? there is no new lidar status map thumbnail link on the stratmap landing page...
i see changes to the organization of the lidar page, but the content is the same with only an exception of an anchor text link to stratmap contracts.

2019-11-25 20:09 UTC, adambreznicky commented on content/markdown/stratmap/elevation-lidar.md
> +<div class="col-md-8">
these nested tags should be indented

2019-11-25 20:10 UTC, adambreznicky commented on content/markdown/stratmap/elevation-lidar.md
> +<h2>TNRIS Lidar Coverage</h2>
numerous nested tags in this file should be properly indented based on parent tags

2019-11-25 20:11 UTC, christoball commented
@ThorTheDestroyer and this is the approach we agreed on. We moved the Lidar status map up in the page and we will revisit the front page at a future date.

2019-11-25 20:12 UTC, christoball commented
@adambreznicky @ThorTheDestroyer we rearranged the stratmap page and will revisit the front page at a later date.

2019-11-25 20:24 UTC, adambreznicky commented
> @ThorTheDestroyer and this is the approach we agreed on. We moved the Lidar status map up in the page and we will revisit the front page at a future date.

right on, sounds good. i agree, the lidar status map is probably more important than the side-by-side slider. glad that just moving it is enough to satisfy the request. maybe next time throw the context/conclusion/decision of y'alls chat into the issue? without it i was unaware of the change in plan during review. super thanks

2019-11-25 20:27 UTC, christoball commented
@adambreznicky I'll be sure to make it clear if there are major changes in the approach to resolving stuff on future issues, that makes sense especially to help review.

2019-11-25 20:29 UTC, christoball commented
@adambreznicky all the different number sections and their colors should be correct now with the latest commit

2019-11-25 20:37 UTC, adambreznicky commented
> @adambreznicky all the different number sections and their colors should be correct now with the latest commit

looks great!

2019-11-25 20:37 UTC, merged