Update historic imagery pricing
TNRIS/tnris.org pull request #170
Opened 2020-03-02 17:04 UTC by christoball

closes #167

2020-03-03 13:34 UTC, JasonKleinert commented on templates/rdc/rdc-sub.njk
> +          <li>$60/ Full Historical Search (multiple years or sites)</li>
Looks like you have an extra space here after "$60/"

2020-03-03 13:36 UTC, JasonKleinert commented on templates/rdc/rdc-sub.njk
> +        <p>$7 digital download delivery (0-10gb)</p>
Did you want a "/" after "$7" like you have on the other lines?

2020-03-03 14:17 UTC, JasonKleinert requested changes
It looks like the formatting needs to be discussed with RDC. They have provided an updated comment to look to on this issue.

2020-03-03 20:36 UTC, christoball commented
@JasonKleinert I've worked out the changes with the RDC and they said it looks good to go on their end.

2020-03-04 14:28 UTC, adambreznicky commented on content/markdown/research-distribution-center/historical-imagery-archive.md
> +  <li>Digital download delivery (0-10gb): <strong>$7.00</strong></li>
please update the (0-10gb) to be the same as the other 2 options: (0-10 GB)

2020-03-04 14:33 UTC, adambreznicky commented
found one inconsistency. when fixed, we can call it and merge/deploy. looks good though!

2020-03-04 15:34 UTC, christoball commented
@adambreznicky fixed in the most recent commit

2020-03-04 16:36 UTC, merged